name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Remove .npmrc # Because of issue with pnpm automatically fetching nodejs executable
        run: rm .npmrc
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: lib
