name: Release
on:
  push:
    branches:
      - master
      - v3

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.x
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Remove .npmrc # Because of issue with pnpm automatically fetching nodejs executable
        run: rm .npmrc
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
